// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package brand

import (
	"goApp/api/brand"
)

type ControllerV1 struct{}

func NewV1() brand.IBrandV1 {
	return &ControllerV1{}
}
