// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package bank

import (
	"goApp/api/bank"
)

type ControllerV1 struct{}

func NewV1() bank.IBankV1 {
	return &ControllerV1{}
}
