
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    version:  "v1.0.0"
    system: "windows"
  gen:
    enums:
      src:  "."
      path: "internal/packed/packed.go"
    dao:
      - link: "mysql:root:123456@tcp(10.10.10.250:3306)/go_jxc"
        descriptionTag: true # 用于指定是否为数据模型结构体属性增加desription的标签, 内容为对应的数据表字段注释. 默认 false
        noModelComment: true # 用于指定是否关闭数据模型结构体属性的注释自动生成, 内容为数据表对应字段的注释. 默认 false
        jsonCase: "CamelLower" # 指定model中生成的数据实体对象中json标签名称规则. 默认 CamelLower
        clear: true # 自动删除数据库中不存在对应数据表的本地dao/do/entity代码文件, 默认 false. 线上环境应设置为fasle
        #typeMapping:
        #  decimal:
        #    type:   decimal.Decimal
        #    import: github.com/shopspring/decimal
  docker:
    build: "-a amd64 -s linux -p temp -ew"
