// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalBankRecordDao is an internal type for wrapping the internal DAO implementation.
type internalBankRecordDao = *internal.BankRecordDao

// bankRecordDao is the data access object for the table bank_record.
// You can define custom methods on it to extend its functionality as needed.
type bankRecordDao struct {
	internalBankRecordDao
}

var (
	// BankRecord is a globally accessible object for table bank_record operations.
	BankRecord = bankRecordDao{
		internal.NewBankRecordDao(),
	}
)

// Add your custom methods and functionality below.
