// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalBrandDao is an internal type for wrapping the internal DAO implementation.
type internalBrandDao = *internal.BrandDao

// brandDao is the data access object for the table brand.
// You can define custom methods on it to extend its functionality as needed.
type brandDao struct {
	internalBrandDao
}

var (
	// Brand is a globally accessible object for table brand operations.
	Brand = brandDao{
		internal.NewBrandDao(),
	}
)

// Add your custom methods and functionality below.
