// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalBuyDao is an internal type for wrapping the internal DAO implementation.
type internalBuyDao = *internal.BuyDao

// buyDao is the data access object for the table buy.
// You can define custom methods on it to extend its functionality as needed.
type buyDao struct {
	internalBuyDao
}

var (
	// Buy is a globally accessible object for table buy operations.
	Buy = buyDao{
		internal.NewBuyDao(),
	}
)

// Add your custom methods and functionality below.
