// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalBuyDetailDao is an internal type for wrapping the internal DAO implementation.
type internalBuyDetailDao = *internal.BuyDetailDao

// buyDetailDao is the data access object for the table buy_detail.
// You can define custom methods on it to extend its functionality as needed.
type buyDetailDao struct {
	internalBuyDetailDao
}

var (
	// BuyDetail is a globally accessible object for table buy_detail operations.
	BuyDetail = buyDetailDao{
		internal.NewBuyDetailDao(),
	}
)

// Add your custom methods and functionality below.
