// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalColorDao is an internal type for wrapping the internal DAO implementation.
type internalColorDao = *internal.ColorDao

// colorDao is the data access object for the table color.
// You can define custom methods on it to extend its functionality as needed.
type colorDao struct {
	internalColorDao
}

var (
	// Color is a globally accessible object for table color operations.
	Color = colorDao{
		internal.NewColorDao(),
	}
)

// Add your custom methods and functionality below.
