// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalCustomerDao is an internal type for wrapping the internal DAO implementation.
type internalCustomerDao = *internal.CustomerDao

// customerDao is the data access object for the table customer.
// You can define custom methods on it to extend its functionality as needed.
type customerDao struct {
	internalCustomerDao
}

var (
	// Customer is a globally accessible object for table customer operations.
	Customer = customerDao{
		internal.NewCustomerDao(),
	}
)

// Add your custom methods and functionality below.
