// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalSaleDao is an internal type for wrapping the internal DAO implementation.
type internalSaleDao = *internal.SaleDao

// saleDao is the data access object for the table sale.
// You can define custom methods on it to extend its functionality as needed.
type saleDao struct {
	internalSaleDao
}

var (
	// Sale is a globally accessible object for table sale operations.
	Sale = saleDao{
		internal.NewSaleDao(),
	}
)

// Add your custom methods and functionality below.
