// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalSaleDetailDao is an internal type for wrapping the internal DAO implementation.
type internalSaleDetailDao = *internal.SaleDetailDao

// saleDetailDao is the data access object for the table sale_detail.
// You can define custom methods on it to extend its functionality as needed.
type saleDetailDao struct {
	internalSaleDetailDao
}

var (
	// SaleDetail is a globally accessible object for table sale_detail operations.
	SaleDetail = saleDetailDao{
		internal.NewSaleDetailDao(),
	}
)

// Add your custom methods and functionality below.
