// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalStockDao is an internal type for wrapping the internal DAO implementation.
type internalStockDao = *internal.StockDao

// stockDao is the data access object for the table stock.
// You can define custom methods on it to extend its functionality as needed.
type stockDao struct {
	internalStockDao
}

var (
	// Stock is a globally accessible object for table stock operations.
	Stock = stockDao{
		internal.NewStockDao(),
	}
)

// Add your custom methods and functionality below.
