// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalSupplierDao is an internal type for wrapping the internal DAO implementation.
type internalSupplierDao = *internal.SupplierDao

// supplierDao is the data access object for the table supplier.
// You can define custom methods on it to extend its functionality as needed.
type supplierDao struct {
	internalSupplierDao
}

var (
	// Supplier is a globally accessible object for table supplier operations.
	Supplier = supplierDao{
		internal.NewSupplierDao(),
	}
)

// Add your custom methods and functionality below.
