// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalUserDao is an internal type for wrapping the internal DAO implementation.
type internalUserDao = *internal.UserDao

// userDao is the data access object for the table user.
// You can define custom methods on it to extend its functionality as needed.
type userDao struct {
	internalUserDao
}

var (
	// User is a globally accessible object for table user operations.
	User = userDao{
		internal.NewUserDao(),
	}
)

// Add your custom methods and functionality below.
