// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalUserRoleDao is an internal type for wrapping the internal DAO implementation.
type internalUserRoleDao = *internal.UserRoleDao

// userRoleDao is the data access object for the table user_role.
// You can define custom methods on it to extend its functionality as needed.
type userRoleDao struct {
	internalUserRoleDao
}

var (
	// UserRole is a globally accessible object for table user_role operations.
	UserRole = userRoleDao{
		internal.NewUserRoleDao(),
	}
)

// Add your custom methods and functionality below.
