// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goApp/internal/dao/internal"
)

// internalWarehouseDao is an internal type for wrapping the internal DAO implementation.
type internalWarehouseDao = *internal.WarehouseDao

// warehouseDao is the data access object for the table warehouse.
// You can define custom methods on it to extend its functionality as needed.
type warehouseDao struct {
	internalWarehouseDao
}

var (
	// Warehouse is a globally accessible object for table warehouse operations.
	Warehouse = warehouseDao{
		internal.NewWarehouseDao(),
	}
)

// Add your custom methods and functionality below.
