// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package color

import (
	"goApp/api/color"
)

type ControllerV1 struct{}

func NewV1() color.IColorV1 {
	return &ControllerV1{}
}
