// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package unit

import (
	"goApp/api/unit"
)

type ControllerV1 struct{}

func NewV1() unit.IUnitV1 {
	return &ControllerV1{}
}
